import type { RulePack } from './types';

/**
 * ECMA Public Equity Offering pack.
 *
 * The citations below are drafting references to the Ethiopian Capital Market
 * Proclamation No. 1248/2021, the Commercial Code Proclamation No. 1243/2021 and
 * the directives issued under them. They are configurable: a firm must confirm
 * article numbers against the gazette edition in force before filing.
 */
export const ecmaEquityPack: RulePack = {
  key: 'ECMA-EQUITY',
  name: 'ECMA Public Equity Offering',
  version: '2026.1',
  authority: 'Ethiopian Capital Market Authority',
  description:
    'Document checklist, compliance rules and prospectus contents for a public offering of shares by an Ethiopian share company.',
  disclaimer:
    'Authority references are drafting aids maintained by the advisory firm. Confirm every article number against the Negarit Gazeta edition and the ECMA directive in force at the filing date before relying on it.',
  outputLabel: 'Prospectus',
  transactionTypes: ['IPO', 'RIGHTS_ISSUE', 'PRIVATE_PLACEMENT'],

  requirements: [
    // ---- corporate -------------------------------------------------------
    { code: 'ECMA-C-001', title: 'Memorandum of Association', category: 'CORPORATE', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Constitutive memorandum as registered, including every subsequent amendment.',
      authorityRef: 'Commercial Code Proc. 1243/2021, Arts. 250–258',
      matchHints: ['memorandum of association', 'memorandum', 'moa'] },
    { code: 'ECMA-C-002', title: 'Articles of Association', category: 'CORPORATE', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Articles of association in force, certified by the Ministry of Trade and Regional Integration.',
      authorityRef: 'Commercial Code Proc. 1243/2021, Arts. 259–264',
      matchHints: ['articles of association', 'aoa', 'bylaws'] },
    { code: 'ECMA-C-003', title: 'Certificate of Commercial Registration', category: 'CORPORATE', mandatory: true, weight: 2, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Current commercial registration certificate showing the registered capital and principal business.',
      authorityRef: 'Commercial Registration & Licensing Proc. 980/2016',
      matchHints: ['commercial registration', 'registration certificate', 'trade register'] },
    { code: 'ECMA-C-004', title: 'Business Licence', category: 'CORPORATE', mandatory: true, weight: 2, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Valid business licence for every line of business carried on by the issuer.',
      authorityRef: 'Commercial Registration & Licensing Proc. 980/2016, Art. 22',
      matchHints: ['business licence', 'business license', 'trade licence'] },
    { code: 'ECMA-C-005', title: 'Shareholder Register', category: 'CORPORATE', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Register of shareholders with holdings, nationality and paid-up amounts as at the latest practicable date.',
      authorityRef: 'Commercial Code Proc. 1243/2021, Art. 300',
      matchHints: ['shareholder register', 'share register', 'register of members'] },
    { code: 'ECMA-C-006', title: 'Capital Subscription & Payment Evidence', category: 'CORPORATE', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Bank confirmations and subscription lists evidencing that subscribed capital has been paid up.',
      authorityRef: 'Commercial Code Proc. 1243/2021, Arts. 273–276',
      matchHints: ['capital subscription', 'paid-up capital', 'bank confirmation', 'subscription list'] },

    // ---- governance ------------------------------------------------------
    { code: 'ECMA-G-001', title: 'Board Resolution Authorising the Offer', category: 'GOVERNANCE', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Minuted board resolution approving the offering, its size, and the appointment of advisers.',
      authorityRef: 'Capital Market Proc. 1248/2021, Art. 55',
      matchHints: ['board resolution', 'resolution of the board', 'directors resolution'] },
    { code: 'ECMA-G-002', title: 'Extraordinary General Meeting Minutes', category: 'GOVERNANCE', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'EGM minutes approving the capital increase and any amendment to the articles.',
      authorityRef: 'Commercial Code Proc. 1243/2021, Arts. 389–401',
      matchHints: ['extraordinary general meeting', 'egm', 'general assembly minutes'] },
    { code: 'ECMA-G-003', title: 'Board & Senior Management Profiles', category: 'GOVERNANCE', mandatory: true, weight: 2, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'CVs, declarations of interest and fit-and-proper declarations for directors and key management.',
      authorityRef: 'Capital Market Proc. 1248/2021, Art. 58; ECMA corporate governance directive',
      matchHints: ['curriculum vitae', 'director profile', 'fit and proper', 'management profile'] },
    { code: 'ECMA-G-004', title: 'Related-Party Transaction Schedule', category: 'GOVERNANCE', mandatory: true, weight: 2, appliesToStage: 'DUE_DILIGENCE',
      description: 'Schedule of transactions with directors, shareholders and affiliates for the review period.',
      authorityRef: 'IAS 24; Commercial Code Proc. 1243/2021, Art. 356',
      matchHints: ['related party', 'related-party', 'affiliate transaction'] },
    { code: 'ECMA-G-005', title: 'Corporate Governance Charter', category: 'GOVERNANCE', mandatory: false, weight: 1, appliesToStage: 'DUE_DILIGENCE',
      description: 'Board charter, committee terms of reference and internal control framework.',
      authorityRef: 'ECMA corporate governance directive',
      matchHints: ['governance charter', 'terms of reference', 'audit committee'] },

    // ---- financial -------------------------------------------------------
    { code: 'ECMA-F-001', title: 'Audited Financial Statements — 3 Years', category: 'FINANCIAL', mandatory: true, weight: 5, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Audited statements for the three financial years preceding the offer, prepared under IFRS.',
      authorityRef: 'Capital Market Proc. 1248/2021, Art. 56; Financial Reporting Proc. 847/2014',
      matchHints: ['audited financial statements', 'statement of financial position', 'annual report', 'balance sheet'] },
    { code: 'ECMA-F-002', title: 'Interim Financial Statements', category: 'FINANCIAL', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Reviewed interim statements where the last audited year-end is more than six months before filing.',
      authorityRef: 'IAS 34; ECMA continuing disclosure directive',
      matchHints: ['interim financial', 'quarterly financial', 'half-year'] },
    { code: 'ECMA-F-003', title: 'Auditor Report & Independence Confirmation', category: 'FINANCIAL', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Signed audit opinion plus confirmation that the auditor is AABE-registered and independent.',
      authorityRef: 'Financial Reporting Proc. 847/2014; AABE registration directive',
      matchHints: ['independent auditor', 'audit report', 'opinion', 'aabe'] },
    { code: 'ECMA-F-004', title: 'Financial Projections & Assumptions', category: 'FINANCIAL', mandatory: true, weight: 3, appliesToStage: 'DUE_DILIGENCE',
      description: 'Five-year projections with the assumption set, sensitivities and the basis of preparation.',
      authorityRef: 'ECMA prospectus contents directive — profit forecast',
      matchHints: ['projection', 'forecast', 'financial model', 'assumptions'] },
    { code: 'ECMA-F-005', title: 'Use of Proceeds Statement', category: 'FINANCIAL', mandatory: true, weight: 3, appliesToStage: 'DUE_DILIGENCE',
      description: 'Itemised application of the offer proceeds with amounts, timing and priority order.',
      authorityRef: 'ECMA prospectus contents directive — use of proceeds',
      matchHints: ['use of proceeds', 'application of proceeds', 'utilisation of funds'] },
    { code: 'ECMA-F-006', title: 'Valuation Report', category: 'FINANCIAL', mandatory: true, weight: 3, appliesToStage: 'DUE_DILIGENCE',
      description: 'Independent valuation supporting the offer price, with methodology and comparables.',
      authorityRef: 'ECMA pricing and valuation directive',
      matchHints: ['valuation report', 'fair value', 'discounted cash flow', 'offer price'] },
    { code: 'ECMA-F-007', title: 'Bank Statements & Facility Agreements', category: 'FINANCIAL', mandatory: true, weight: 2, appliesToStage: 'DUE_DILIGENCE',
      description: 'Principal bank statements and all borrowing facilities, including security granted.',
      authorityRef: 'Commercial Code Proc. 1243/2021, Art. 356',
      matchHints: ['bank statement', 'facility agreement', 'loan agreement', 'overdraft'] },

    // ---- tax -------------------------------------------------------------
    { code: 'ECMA-T-001', title: 'Tax Clearance Certificate', category: 'TAX', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
      description: 'Current tax clearance from the Ministry of Revenue covering all registered tax types.',
      authorityRef: 'Tax Administration Proc. 983/2016, Art. 15',
      matchHints: ['tax clearance', 'ministry of revenue', 'tax certificate'] },
    { code: 'ECMA-T-002', title: 'VAT & Withholding Filings', category: 'TAX', mandatory: true, weight: 2, appliesToStage: 'DUE_DILIGENCE',
      description: 'Filed VAT and withholding returns for the review period with payment evidence.',
      authorityRef: 'VAT Proc. 285/2002 as amended; Income Tax Proc. 979/2016',
      matchHints: ['vat return', 'withholding tax', 'tax declaration'] },
    { code: 'ECMA-T-003', title: 'Tax Assessment & Dispute Schedule', category: 'TAX', mandatory: false, weight: 2, appliesToStage: 'DUE_DILIGENCE',
      description: 'Open assessments, objections and appeals before the Tax Appeal Commission or courts.',
      authorityRef: 'Tax Administration Proc. 983/2016, Arts. 54–56',
      matchHints: ['tax assessment', 'tax appeal', 'objection'] },

    // ---- legal -----------------------------------------------------------
    { code: 'ECMA-L-001', title: 'Litigation & Contingency Schedule', category: 'LEGAL', mandatory: true, weight: 3, appliesToStage: 'DUE_DILIGENCE',
      description: 'All pending and threatened proceedings with court, claim value, stage and counsel opinion.',
      authorityRef: 'ECMA prospectus contents directive — legal proceedings; IAS 37',
      matchHints: ['litigation', 'court case', 'legal proceedings', 'contingent liability'] },
    { code: 'ECMA-L-002', title: 'Material Contracts', category: 'LEGAL', mandatory: true, weight: 3, appliesToStage: 'DUE_DILIGENCE',
      description: 'Contracts material to the business: supply, distribution, offtake, joint venture, leases.',
      authorityRef: 'ECMA prospectus contents directive — material contracts',
      matchHints: ['material contract', 'supply agreement', 'joint venture', 'lease agreement'] },
    { code: 'ECMA-L-003', title: 'Title Deeds & Land Holding Certificates', category: 'LEGAL', mandatory: true, weight: 3, appliesToStage: 'DUE_DILIGENCE',
      description: 'Lease-hold certificates and title documents for every material property interest.',
      authorityRef: 'Urban Land Lease Holding Proc. 721/2011',
      matchHints: ['title deed', 'land holding', 'lease certificate', 'land certificate'] },
    { code: 'ECMA-L-004', title: 'Intellectual Property Register', category: 'LEGAL', mandatory: false, weight: 1, appliesToStage: 'DUE_DILIGENCE',
      description: 'Trademarks, patents and licences registered with the Ethiopian Intellectual Property Authority.',
      authorityRef: 'Trademark Registration Proc. 501/2006',
      matchHints: ['trademark', 'patent', 'intellectual property'] },
    { code: 'ECMA-L-005', title: 'Employment & Pension Compliance', category: 'LEGAL', mandatory: true, weight: 2, appliesToStage: 'DUE_DILIGENCE',
      description: 'Employment contracts, collective agreements and private-organisation pension contributions.',
      authorityRef: 'Labour Proc. 1156/2019; Private Organisation Employees Pension Proc. 1268/2022',
      matchHints: ['employment contract', 'collective agreement', 'pension', 'labour'] },
    { code: 'ECMA-L-006', title: 'Insurance Policy Schedule', category: 'LEGAL', mandatory: false, weight: 1, appliesToStage: 'DUE_DILIGENCE',
      description: 'Current insurance cover for assets, liability and key persons.',
      authorityRef: 'Insurance Business Proc. 746/2012',
      matchHints: ['insurance policy', 'cover note', 'policy schedule'] },

    // ---- regulatory ------------------------------------------------------
    { code: 'ECMA-R-001', title: 'Sector Regulator No-Objection', category: 'REGULATORY', mandatory: false, weight: 3, appliesToStage: 'DUE_DILIGENCE',
      description: 'No-objection from the sector regulator (NBE, EEA, ECA) where the issuer is in a regulated sector.',
      authorityRef: 'Capital Market Proc. 1248/2021, Art. 60',
      matchHints: ['no objection', 'no-objection', 'national bank of ethiopia', 'regulator approval'] },
    { code: 'ECMA-R-002', title: 'Environmental & Social Impact Assessment', category: 'REGULATORY', mandatory: false, weight: 2, appliesToStage: 'DUE_DILIGENCE',
      description: 'ESIA and the environmental authorisation for projects requiring one.',
      authorityRef: 'Environmental Impact Assessment Proc. 299/2002',
      matchHints: ['environmental impact', 'esia', 'environmental clearance'] },
    { code: 'ECMA-R-003', title: 'AML / KYC Pack', category: 'REGULATORY', mandatory: true, weight: 3, appliesToStage: 'ONBOARDING',
      description: 'Beneficial ownership declaration, PEP screening and identity documents for controllers.',
      authorityRef: 'Prevention & Suppression of Money Laundering Proc. 780/2013',
      matchHints: ['beneficial owner', 'kyc', 'anti-money laundering', 'pep', 'identity document'] },
    { code: 'ECMA-R-004', title: 'Underwriting / Placement Agreement', category: 'REGULATORY', mandatory: false, weight: 2, appliesToStage: 'PROSPECTUS_DRAFTING',
      description: 'Executed underwriting or best-efforts placement agreement with the licensed dealer.',
      authorityRef: 'Capital Market Proc. 1248/2021, Arts. 38–44',
      matchHints: ['underwriting agreement', 'placement agreement', 'dealer agreement'] },
    { code: 'ECMA-R-005', title: 'Transfer Agent & Registrar Appointment', category: 'REGULATORY', mandatory: false, weight: 1, appliesToStage: 'PROSPECTUS_DRAFTING',
      description: 'Appointment of the share registrar and the central securities depository arrangements.',
      authorityRef: 'Capital Market Proc. 1248/2021, Art. 45',
      matchHints: ['transfer agent', 'registrar', 'depository', 'csd'] },
  ],

  rules: [
    // --- LEGAL ------------------------------------------------------------
    { id: 'L-001', agent: 'LEGAL', appliesTo: ['ECMA-C-002'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'HIGH',
      title: 'Articles silent on share transfer restrictions',
      detail: 'A share company seeking a public listing must state how shares transfer and whether any restriction survives admission. Articles that omit a transfer clause create uncertainty for subscribers and are routinely queried on filing.',
      citation: 'Commercial Code Proc. 1243/2021, Arts. 304–310',
      recommendation: 'Amend the articles by extraordinary general meeting to insert a transfer clause consistent with free transferability of listed shares, and file the amendment before submission.',
      phrases: ['transfer of shares', 'share transfer', 'transferability'] },
    { id: 'L-002', agent: 'LEGAL', appliesTo: ['ECMA-C-002'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'MEDIUM',
      title: 'Articles do not provide for an audit committee',
      detail: 'ECMA governance expectations for a public issuer include a standing audit committee with a defined composition and mandate. The articles as drafted do not establish one.',
      citation: 'ECMA corporate governance directive; Commercial Code Proc. 1243/2021, Art. 347',
      recommendation: 'Insert an audit committee article specifying composition, independence, quorum and reporting line to the board.',
      phrases: ['audit committee', 'audit and risk committee'] },
    { id: 'L-003', agent: 'LEGAL', appliesTo: ['ECMA-G-002'], kind: 'MUST_CONTAIN_ANY', gapType: 'REGULATORY', severity: 'CRITICAL',
      title: 'EGM minutes do not evidence the statutory quorum',
      detail: 'A resolution amending the articles or increasing capital is valid only if the statutory quorum and majority are met and recorded. The minutes do not state attendance as a proportion of subscribed capital.',
      citation: 'Commercial Code Proc. 1243/2021, Arts. 394–399',
      recommendation: 'Obtain a certified extract stating shares represented, quorum achieved and the majority by which each resolution passed; re-convene if the quorum was not met.',
      phrases: ['quorum', 'shares represented', 'majority'] },
    { id: 'L-004', agent: 'LEGAL', appliesTo: ['ECMA-G-001'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'HIGH',
      title: 'Board resolution does not fix the offer size or price basis',
      detail: 'The authorising resolution should fix, or delegate within stated limits, the number of shares offered and the pricing basis. An open-ended authorisation is not sufficient for filing.',
      citation: 'Capital Market Proc. 1248/2021, Art. 55',
      recommendation: 'Pass a supplementary resolution stating the maximum number of shares, the price or price range, and the delegation limits.',
      phrases: ['number of shares', 'offer price', 'price range', 'par value'] },
    { id: 'L-005', agent: 'LEGAL', appliesTo: ['ECMA-L-001'], kind: 'MUST_CONTAIN_ANY', gapType: 'DISCLOSURE', severity: 'HIGH',
      title: 'Litigation schedule lacks quantification or counsel opinion',
      detail: 'Each matter must carry a claim value and counsel\'s assessment of the likely outcome so that the provision and the risk-factor disclosure can be tested.',
      citation: 'IAS 37; ECMA prospectus contents directive — legal proceedings',
      recommendation: 'Request an updated litigation schedule with claim amounts in ETB, forum, procedural stage and external counsel\'s probability assessment for each matter.',
      phrases: ['claim amount', 'counsel', 'opinion', 'probable'] },
    { id: 'L-006', agent: 'LEGAL', appliesTo: ['ECMA-L-003'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'HIGH',
      title: 'Land holding evidence does not confirm lease term or encumbrance status',
      detail: 'Urban land is held on lease. The file must show the unexpired lease term and any mortgage or caveat registered against the holding, as these bear directly on asset value.',
      citation: 'Urban Land Lease Holding Proc. 721/2011, Arts. 18–24',
      recommendation: 'Obtain a fresh encumbrance search from the land administration bureau for every material holding and reconcile it to the fixed-asset register.',
      phrases: ['lease period', 'lease term', 'encumbrance', 'mortgage'] },
    { id: 'L-007', agent: 'LEGAL', appliesTo: ['ECMA-C-005'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'MEDIUM',
      title: 'Shareholder register does not identify beneficial ownership',
      detail: 'Where shares are held through nominees or corporate vehicles, the ultimate beneficial owner must be identified for AML and disclosure purposes.',
      citation: 'Proc. 780/2013; Capital Market Proc. 1248/2021, Art. 58',
      recommendation: 'Collect beneficial ownership declarations for every holder above the disclosure threshold and reconcile them to the register.',
      phrases: ['beneficial owner', 'ultimate owner', 'nominee'] },
    { id: 'L-008', agent: 'LEGAL', appliesTo: ['ECMA-L-002'], kind: 'MUST_NOT_CONTAIN', gapType: 'COMPLIANCE', severity: 'HIGH',
      title: 'Material contract contains a change-of-control trigger',
      detail: 'A change-of-control or assignment-on-listing clause can allow a counterparty to terminate on completion of the offer. This is a disclosable risk and may require a waiver.',
      citation: 'ECMA prospectus contents directive — material contracts',
      recommendation: 'Seek a written waiver or consent from the counterparty before filing, and disclose the clause as a risk factor if no waiver is obtained.',
      phrases: ['change of control', 'change in control'] },
    { id: 'L-009', agent: 'LEGAL', appliesTo: ['ECMA-L-005'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'MEDIUM',
      title: 'Pension contribution compliance not evidenced',
      detail: 'Private-organisation pension contributions are a statutory charge; arrears become a preferential liability and must be quantified before the offer.',
      citation: 'Private Organisation Employees Pension Proc. 1268/2022',
      recommendation: 'Obtain a contribution statement from the Private Organisations Employees Social Security Agency covering the full review period.',
      phrases: ['pension contribution', 'social security', 'provident'] },
    { id: 'L-010', agent: 'LEGAL', appliesTo: ['ECMA-R-003'], kind: 'MUST_CONTAIN_ANY', gapType: 'REGULATORY', severity: 'CRITICAL',
      title: 'AML pack does not evidence PEP screening',
      detail: 'Controllers and beneficial owners must be screened for politically exposed person status; the file must record the screening and its outcome.',
      citation: 'Proc. 780/2013; FIC customer due diligence directive',
      recommendation: 'Run and document PEP and sanctions screening for every controller, and escalate any positive match for enhanced due diligence.',
      phrases: ['politically exposed', 'pep', 'sanctions screening'] },

    // --- FINANCIAL --------------------------------------------------------
    { id: 'F-001', agent: 'FINANCIAL', appliesTo: ['ECMA-F-001'], kind: 'MUST_CONTAIN_ANY', gapType: 'FINANCIAL', severity: 'CRITICAL',
      title: 'Statements do not assert IFRS compliance',
      detail: 'The statements must contain an explicit and unreserved statement of compliance with IFRS. Without it the basis of preparation cannot be accepted for a public offering.',
      citation: 'IAS 1.16; Financial Reporting Proc. 847/2014',
      recommendation: 'Request re-issued statements carrying an explicit IFRS compliance statement, or a reconciliation from the framework used to IFRS.',
      phrases: ['International Financial Reporting Standards', 'IFRS'] },
    { id: 'F-002', agent: 'FINANCIAL', appliesTo: ['ECMA-F-001'], kind: 'MUST_CONTAIN', gapType: 'FINANCIAL', severity: 'HIGH',
      title: 'Primary statement set is incomplete',
      detail: 'A complete set comprises the statement of financial position, profit or loss and other comprehensive income, changes in equity, cash flows and the notes. One or more is absent.',
      citation: 'IAS 1.10',
      recommendation: 'Obtain the missing primary statement(s) and the accompanying notes before commencing substantive financial due diligence.',
      phrases: ['statement of financial position', 'statement of cash flows', 'changes in equity'] },
    { id: 'F-003', agent: 'FINANCIAL', appliesTo: ['ECMA-F-003'], kind: 'MUST_NOT_CONTAIN', gapType: 'FINANCIAL', severity: 'CRITICAL',
      title: 'Audit opinion is modified',
      detail: 'A qualified, adverse or disclaimed opinion is a material impediment to a public offering and must be resolved or fully explained and quantified.',
      citation: 'ISA 705; Capital Market Proc. 1248/2021, Art. 56',
      recommendation: 'Obtain management\'s remediation plan and the auditor\'s view on removal of the modification; quantify the effect and disclose it prominently if it persists.',
      phrases: ['qualified opinion', 'adverse opinion', 'disclaimer of opinion', 'except for'] },
    { id: 'F-004', agent: 'FINANCIAL', appliesTo: ['ECMA-F-001', 'ECMA-F-002'], kind: 'MUST_NOT_CONTAIN', gapType: 'FINANCIAL', severity: 'CRITICAL',
      title: 'Going-concern material uncertainty disclosed',
      detail: 'A material uncertainty related to going concern must be disclosed as a principal risk factor and supported by a funding plan covering at least twelve months from filing.',
      citation: 'IAS 1.25; ISA 570',
      recommendation: 'Obtain a board-approved cash-flow forecast and funding confirmations covering twelve months from the expected filing date, and draft the corresponding risk factor.',
      phrases: ['material uncertainty', 'going concern', 'ability to continue'] },
    { id: 'F-005', agent: 'FINANCIAL', appliesTo: ['ECMA-F-001'], kind: 'MUST_CONTAIN_ANY', gapType: 'DISCLOSURE', severity: 'HIGH',
      title: 'Related-party disclosures absent from the notes',
      detail: 'IAS 24 requires disclosure of relationships, transactions and outstanding balances with related parties, including key management compensation.',
      citation: 'IAS 24.13–24.18',
      recommendation: 'Request a complete related-party note and reconcile it to the related-party schedule and the board register of interests.',
      phrases: ['related party', 'related parties', 'key management personnel'] },
    { id: 'F-006', agent: 'FINANCIAL', appliesTo: ['ECMA-F-002'], kind: 'DATE_FRESHNESS', gapType: 'REGULATORY', severity: 'HIGH', maxAgeMonths: 9,
      title: 'Financial information is stale for filing',
      detail: 'The latest audited or reviewed period end must fall within the staleness window at the filing date, otherwise interim information must be added.',
      citation: 'ECMA prospectus contents directive — financial information currency',
      recommendation: 'Commission reviewed interim statements covering the period to the most recent quarter end and update the prospectus financial section.',
      phrases: [] },
    { id: 'F-007', agent: 'FINANCIAL', appliesTo: ['ECMA-F-004'], kind: 'MUST_CONTAIN_ANY', gapType: 'DISCLOSURE', severity: 'HIGH',
      title: 'Projections lack a stated assumption basis',
      detail: 'A profit forecast must be accompanied by the principal assumptions, stated so that a reader can assess whether they are within management\'s control.',
      citation: 'ECMA prospectus contents directive — profit forecast',
      recommendation: 'Require a written assumption set distinguishing controllable from non-controllable assumptions, plus a sensitivity analysis on the two most material drivers.',
      phrases: ['assumption', 'basis of preparation', 'sensitivity'] },
    { id: 'F-008', agent: 'FINANCIAL', appliesTo: ['ECMA-F-005'], kind: 'NUMERIC_PRESENT', gapType: 'DISCLOSURE', severity: 'HIGH',
      pattern: '\\d[\\d,\\.]{3,}',
      title: 'Use of proceeds is not quantified',
      detail: 'Proceeds must be allocated to stated uses in amounts, with the order of priority if the offer is not fully subscribed.',
      citation: 'ECMA prospectus contents directive — use of proceeds',
      recommendation: 'Obtain an itemised table of proceeds by use, amount and timing, together with the priority order under a partial-subscription scenario.',
      phrases: [] },
    { id: 'F-009', agent: 'FINANCIAL', appliesTo: ['ECMA-F-006'], kind: 'MUST_CONTAIN_ANY', gapType: 'FINANCIAL', severity: 'HIGH',
      title: 'Valuation does not disclose its methodology',
      detail: 'The pricing basis must name the valuation methods applied, the weighting between them and the key inputs, so that the offer price can be tested.',
      citation: 'ECMA pricing and valuation directive; IVS 105',
      recommendation: 'Request the valuer\'s methodology section including discount rate build-up, terminal assumptions and the comparable set.',
      phrases: ['discounted cash flow', 'market approach', 'net asset value', 'comparable'] },
    { id: 'F-010', agent: 'FINANCIAL', appliesTo: ['ECMA-F-007'], kind: 'MUST_CONTAIN_ANY', gapType: 'FINANCIAL', severity: 'MEDIUM',
      title: 'Borrowing covenants not evidenced',
      detail: 'Facility agreements typically carry financial covenants whose breach would be a disclosable event. The file does not show the covenant set or current headroom.',
      citation: 'IFRS 7.18–7.19',
      recommendation: 'Extract all financial covenants, compute headroom at the latest balance sheet date, and obtain lender confirmations of no default.',
      phrases: ['covenant', 'default', 'gearing ratio', 'debt service'] },
    { id: 'F-011', agent: 'FINANCIAL', appliesTo: ['ECMA-T-001'], kind: 'DATE_FRESHNESS', gapType: 'REGULATORY', severity: 'HIGH', maxAgeMonths: 12,
      title: 'Tax clearance certificate is out of date',
      detail: 'The tax clearance must be current at filing and must cover every registered tax type.',
      citation: 'Tax Administration Proc. 983/2016, Art. 15',
      recommendation: 'Apply for a fresh clearance certificate and confirm it lists VAT, profit tax, withholding and employment income tax.',
      phrases: [] },

    // --- EDITORIAL / PROSPECTUS ------------------------------------------
    { id: 'E-001', agent: 'PROSPECTUS', appliesTo: ['*'], kind: 'EDITORIAL', gapType: 'EDITORIAL', severity: 'LOW',
      title: 'Placeholder text left in the document',
      detail: 'Unresolved placeholders indicate the document has not been finalised and will be rejected on a completeness check.',
      citation: 'ECMA filing completeness check',
      recommendation: 'Resolve every placeholder before circulating the document for review.',
      phrases: ['[tbd]', 'tbd', 'lorem ipsum', 'xxx', '[insert', 'to be confirmed', 'tbc'] },
    { id: 'E-002', agent: 'PROSPECTUS', appliesTo: ['*'], kind: 'EDITORIAL', gapType: 'EDITORIAL', severity: 'LOW',
      title: 'Document is undated or unsigned',
      detail: 'A document submitted in support of a filing must show its date and the signature or seal of the person giving it.',
      citation: 'ECMA filing completeness check',
      recommendation: 'Return the document to the client for dating and execution.',
      phrases: ['signature', 'signed', 'date'] },
    { id: 'E-003', agent: 'PROSPECTUS', appliesTo: ['*'], kind: 'MUST_NOT_CONTAIN', gapType: 'EDITORIAL', severity: 'MEDIUM',
      title: 'Forward-looking language without a safe-harbour qualifier',
      detail: 'Projections and expectations stated as fact, without the cautionary statement, create prospectus liability exposure.',
      citation: 'Capital Market Proc. 1248/2021, Arts. 63–66 (prospectus liability)',
      recommendation: 'Qualify forward-looking statements and add the cautionary note on forward-looking information to the front of the prospectus.',
      phrases: ['will guarantee', 'guaranteed return', 'is certain to', 'risk-free return'] },
  ],

  prospectus: [
    { code: 'P-00', sequence: 0, heading: 'Cover Page and Offer Summary', requiredBy: 'ECMA prospectus contents directive, Part I', minWords: 220,
      guidance: 'Issuer name and legal form, securities offered, offer size and price, opening and closing dates, advisers, the ECMA approval statement and the standard investor warning.',
      sourceRequirements: ['ECMA-C-001', 'ECMA-G-001', 'ECMA-F-006'] },
    { code: 'P-01', sequence: 1, heading: 'Important Notice and Disclaimers', requiredBy: 'Capital Market Proc. 1248/2021, Arts. 63–66', minWords: 260,
      guidance: 'Responsibility statement of the directors, forward-looking statement caution, restrictions on distribution, and the statement that ECMA approval is not an endorsement of the merits.',
      sourceRequirements: ['ECMA-G-001', 'ECMA-G-003'] },
    { code: 'P-02', sequence: 2, heading: 'Definitions and Abbreviations', requiredBy: 'ECMA prospectus contents directive, Part I', minWords: 180,
      guidance: 'Defined terms used consistently through the document, including Ethiopian statutory references and currency conventions.', sourceRequirements: [] },
    { code: 'P-03', sequence: 3, heading: 'Corporate Directory', requiredBy: 'ECMA prospectus contents directive, Part II', minWords: 150,
      guidance: 'Registered office, directors, company secretary, auditors, legal advisers, transaction adviser, receiving banks and registrar with addresses and licence numbers.',
      sourceRequirements: ['ECMA-C-003', 'ECMA-G-003', 'ECMA-R-005'] },
    { code: 'P-04', sequence: 4, heading: 'Particulars of the Offer', requiredBy: 'ECMA prospectus contents directive, Part III', minWords: 400,
      guidance: 'Securities offered, rights attaching, offer price and basis, minimum subscription, allotment policy, timetable, application procedure and payment mechanics.',
      sourceRequirements: ['ECMA-G-001', 'ECMA-G-002', 'ECMA-F-006', 'ECMA-R-004'] },
    { code: 'P-05', sequence: 5, heading: 'Use of Proceeds', requiredBy: 'ECMA prospectus contents directive, Part III', minWords: 300,
      guidance: 'Itemised application of net proceeds with amounts and timing, the priority order under partial subscription, and the estimated offer expenses.',
      sourceRequirements: ['ECMA-F-005'] },
    { code: 'P-06', sequence: 6, heading: 'Information on the Issuer', requiredBy: 'ECMA prospectus contents directive, Part IV', minWords: 500,
      guidance: 'Incorporation history, group structure, principal activities, markets served, production or service capacity, properties and employees.',
      sourceRequirements: ['ECMA-C-001', 'ECMA-C-003', 'ECMA-C-004', 'ECMA-L-003', 'ECMA-L-005'] },
    { code: 'P-07', sequence: 7, heading: 'Industry and Market Overview', requiredBy: 'ECMA prospectus contents directive, Part IV', minWords: 450,
      guidance: 'Sector size and growth, regulatory setting, competitive position and the source of every market statistic cited.', sourceRequirements: [] },
    { code: 'P-08', sequence: 8, heading: 'Directors, Management and Corporate Governance', requiredBy: 'Capital Market Proc. 1248/2021, Art. 58', minWords: 450,
      guidance: 'Board composition and independence, biographies, committees, remuneration, shareholdings, conflicts and the governance framework applied.',
      sourceRequirements: ['ECMA-G-003', 'ECMA-G-005', 'ECMA-C-005'] },
    { code: 'P-09', sequence: 9, heading: 'Share Capital and Shareholding Structure', requiredBy: 'Commercial Code Proc. 1243/2021, Arts. 273–300', minWords: 350,
      guidance: 'Authorised, subscribed and paid-up capital, capital history, substantial shareholders, dilution on the offer and lock-up arrangements.',
      sourceRequirements: ['ECMA-C-005', 'ECMA-C-006', 'ECMA-G-002'] },
    { code: 'P-10', sequence: 10, heading: 'Financial Information', requiredBy: 'Capital Market Proc. 1248/2021, Art. 56', minWords: 600,
      guidance: 'Three-year audited summary, interim figures, accounting policies, key ratios and the reporting accountant\'s report.',
      sourceRequirements: ['ECMA-F-001', 'ECMA-F-002', 'ECMA-F-003'] },
    { code: 'P-11', sequence: 11, heading: 'Management Discussion and Analysis', requiredBy: 'ECMA prospectus contents directive, Part V', minWords: 550,
      guidance: 'Period-on-period explanation of revenue, margin, liquidity and capital resources, with the drivers behind each movement.',
      sourceRequirements: ['ECMA-F-001', 'ECMA-F-007'] },
    { code: 'P-12', sequence: 12, heading: 'Profit Forecast and Assumptions', requiredBy: 'ECMA prospectus contents directive, Part V', minWords: 350,
      guidance: 'The forecast, the principal assumptions split between controllable and non-controllable, sensitivities and the reporting accountant\'s opinion.',
      sourceRequirements: ['ECMA-F-004'] },
    { code: 'P-13', sequence: 13, heading: 'Risk Factors', requiredBy: 'ECMA prospectus contents directive, Part VI', minWords: 700,
      guidance: 'Risks specific to the issuer, the industry and the securities, ordered by materiality, each stating the risk, its potential effect and any mitigation. Generic risks are to be avoided.',
      sourceRequirements: ['ECMA-L-001', 'ECMA-F-001', 'ECMA-R-001'] },
    { code: 'P-14', sequence: 14, heading: 'Legal and Regulatory Matters', requiredBy: 'ECMA prospectus contents directive, Part VII', minWords: 400,
      guidance: 'Litigation, material contracts, licences and permits, property title, intellectual property and regulatory approvals obtained.',
      sourceRequirements: ['ECMA-L-001', 'ECMA-L-002', 'ECMA-L-003', 'ECMA-L-004', 'ECMA-R-001'] },
    { code: 'P-15', sequence: 15, heading: 'Taxation', requiredBy: 'Income Tax Proc. 979/2016', minWords: 280,
      guidance: 'Tax treatment of dividends and capital gains for resident and non-resident holders, withholding obligations and stamp duty.',
      sourceRequirements: ['ECMA-T-001', 'ECMA-T-002'] },
    { code: 'P-16', sequence: 16, heading: 'Statutory and General Information', requiredBy: 'ECMA prospectus contents directive, Part VIII', minWords: 320,
      guidance: 'Consents of experts, documents available for inspection, material changes since the last balance sheet date and the directors\' declaration.',
      sourceRequirements: ['ECMA-F-003', 'ECMA-G-001'] },
    { code: 'P-17', sequence: 17, heading: 'Application Form and Instructions', requiredBy: 'ECMA prospectus contents directive, Part IX', minWords: 220,
      guidance: 'The application form, instructions for completion, receiving bank details and the declaration to be signed by the applicant.',
      sourceRequirements: ['ECMA-R-004', 'ECMA-R-005'] },
  ],

  milestones: [
    { name: 'Engagement letter signed & retainer received', description: 'Scope, fee and timetable agreed; KYC completed.', sequence: 1, offsetDays: 0, feeShare: 0.2 },
    { name: 'Document collection at threshold', description: 'Mandated document set uploaded and accepted to the agreed completeness threshold.', sequence: 2, offsetDays: 45, feeShare: 0.15 },
    { name: 'Legal & financial due diligence reports delivered', description: 'Both due-diligence reports reviewed and signed off by the responsible experts.', sequence: 3, offsetDays: 90, feeShare: 0.25 },
    { name: 'Risk register and disclosure strategy approved', description: 'Scored risk register approved by the board of the issuer.', sequence: 4, offsetDays: 110, feeShare: 0.1 },
    { name: 'Prospectus draft delivered', description: 'Full prospectus draft delivered for issuer and counsel review.', sequence: 5, offsetDays: 140, feeShare: 0.2 },
    { name: 'ECMA filing and approval', description: 'Submission lodged with ECMA and approval obtained.', sequence: 6, offsetDays: 180, feeShare: 0.1 },
  ],
};
