import type { RulePack, RequirementSpec, RuleSpec } from './types';
import { ecmaEquityPack } from './ecma-equity';

const keep = (codes: string[]): RequirementSpec[] =>
  ecmaEquityPack.requirements.filter((r) => codes.includes(r.code));

const maOnly: RequirementSpec[] = [
  { code: 'MA-001', title: 'Term Sheet / Heads of Terms', category: 'LEGAL', mandatory: true, weight: 4, appliesToStage: 'ONBOARDING',
    description: 'Signed heads of terms setting the structure, price basis, conditions and exclusivity.',
    authorityRef: 'Commercial Code Proc. 1243/2021, Arts. 549–560 (amalgamation)',
    matchHints: ['term sheet', 'heads of terms', 'letter of intent', 'mou'] },
  { code: 'MA-002', title: 'Share Purchase / Merger Agreement', category: 'LEGAL', mandatory: true, weight: 5, appliesToStage: 'PROSPECTUS_DRAFTING',
    description: 'Draft or executed transaction agreement with warranties, indemnities and completion mechanics.',
    authorityRef: 'Commercial Code Proc. 1243/2021, Arts. 549–575',
    matchHints: ['share purchase agreement', 'merger agreement', 'spa', 'sale agreement'] },
  { code: 'MA-003', title: 'Trade Competition Clearance', category: 'REGULATORY', mandatory: true, weight: 4, appliesToStage: 'DUE_DILIGENCE',
    description: 'Merger notification to and clearance from the Trade Competition and Consumer Protection Authority.',
    authorityRef: 'Trade Competition & Consumer Protection Proc. 813/2013, Arts. 9–14',
    matchHints: ['competition authority', 'merger notification', 'clearance', 'tccpa'] },
  { code: 'MA-004', title: 'Target Data Room Index', category: 'CORPORATE', mandatory: true, weight: 3, appliesToStage: 'DOCUMENT_COLLECTION',
    description: 'Index of the target\'s data room with completeness status against the request list.',
    authorityRef: 'Engagement scope',
    matchHints: ['data room', 'index', 'request list'] },
  { code: 'MA-005', title: 'Purchase Price Allocation & Completion Accounts', category: 'FINANCIAL', mandatory: true, weight: 4, appliesToStage: 'DUE_DILIGENCE',
    description: 'Basis of the price, net debt and working-capital adjustment mechanics, and the completion accounts policy.',
    authorityRef: 'IFRS 3; transaction agreement',
    matchHints: ['purchase price', 'completion accounts', 'net debt', 'working capital adjustment'] },
  { code: 'MA-006', title: 'Employee & Pension Transfer Plan', category: 'LEGAL', mandatory: true, weight: 3, appliesToStage: 'DUE_DILIGENCE',
    description: 'Treatment of employees on transfer, consultation record and pension liability allocation.',
    authorityRef: 'Labour Proc. 1156/2019, Art. 17; Proc. 1268/2022',
    matchHints: ['employee transfer', 'redundancy', 'consultation', 'pension transfer'] },
];

const maRules: RuleSpec[] = [
  { id: 'M-001', agent: 'LEGAL', appliesTo: ['MA-003'], kind: 'MUST_CONTAIN_ANY', gapType: 'REGULATORY', severity: 'CRITICAL',
    title: 'Competition clearance not evidenced',
    detail: 'A merger meeting the notification thresholds may not be implemented before clearance; completing without it exposes the parties to penalties and unwinding.',
    citation: 'Trade Competition & Consumer Protection Proc. 813/2013, Arts. 9–14',
    recommendation: 'Compute the turnover and asset thresholds, notify the Authority, and make completion conditional on clearance.',
    phrases: ['clearance', 'approved', 'no objection', 'authorisation'] },
  { id: 'M-002', agent: 'LEGAL', appliesTo: ['MA-002'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'HIGH',
    title: 'Transaction agreement lacks warranty and indemnity protection',
    detail: 'Without warranties and indemnities the buyer carries undisclosed liabilities identified in due diligence with no contractual recourse.',
    citation: 'Commercial Code Proc. 1243/2021; market practice',
    recommendation: 'Negotiate a warranty schedule mapped to the due-diligence findings, with specific indemnities for each identified exposure.',
    phrases: ['warrant', 'warranties', 'indemnity', 'indemnify'] },
  { id: 'M-003', agent: 'FINANCIAL', appliesTo: ['MA-005'], kind: 'MUST_CONTAIN_ANY', gapType: 'FINANCIAL', severity: 'HIGH',
    title: 'Price adjustment mechanism not defined',
    detail: 'Absent a defined net-debt and working-capital mechanic, the price is exposed to leakage between signing and completion.',
    citation: 'IFRS 3; transaction agreement',
    recommendation: 'Define target working capital, the net debt items, the completion accounts policy and the dispute-resolution route for the adjustment.',
    phrases: ['working capital', 'net debt', 'adjustment', 'locked box'] },
  { id: 'M-004', agent: 'LEGAL', appliesTo: ['MA-006'], kind: 'MUST_CONTAIN_ANY', gapType: 'COMPLIANCE', severity: 'MEDIUM',
    title: 'Employee consultation not documented',
    detail: 'Transfers affecting employment terms require consultation; an undocumented process is a common source of post-completion claims.',
    citation: 'Labour Proc. 1156/2019, Arts. 17 and 28',
    recommendation: 'Document the consultation timetable, the notices issued and the union or representative responses.',
    phrases: ['consultation', 'notice', 'union', 'representative'] },
];

export const maPack: RulePack = {
  key: 'MA-ETH',
  name: 'Ethiopian M&A / Restructuring',
  version: '2026.1',
  authority: 'Commercial Code & Trade Competition Authority',
  description: 'Due-diligence checklist, compliance rules and report contents for a merger, acquisition or corporate restructuring.',
  disclaimer: ecmaEquityPack.disclaimer,
  outputLabel: 'Due Diligence Report',
  transactionTypes: ['MA', 'RESTRUCTURING', 'VALUATION'],
  requirements: [
    ...keep([
      'ECMA-C-001', 'ECMA-C-002', 'ECMA-C-003', 'ECMA-C-004', 'ECMA-C-005', 'ECMA-C-006',
      'ECMA-G-001', 'ECMA-G-002', 'ECMA-G-003', 'ECMA-G-004',
      'ECMA-F-001', 'ECMA-F-002', 'ECMA-F-003', 'ECMA-F-004', 'ECMA-F-006', 'ECMA-F-007',
      'ECMA-T-001', 'ECMA-T-002', 'ECMA-T-003',
      'ECMA-L-001', 'ECMA-L-002', 'ECMA-L-003', 'ECMA-L-004', 'ECMA-L-005', 'ECMA-L-006',
      'ECMA-R-002', 'ECMA-R-003',
    ]),
    ...maOnly,
  ],
  rules: [
    ...ecmaEquityPack.rules.filter((r) => !['F-006', 'F-008', 'E-003'].includes(r.id)),
    ...maRules,
  ],
  prospectus: [
    { code: 'M-P0', sequence: 0, heading: 'Transaction Summary', requiredBy: 'Engagement scope', minWords: 250,
      guidance: 'Parties, structure, consideration, conditions precedent and the indicative timetable.', sourceRequirements: ['MA-001', 'MA-002'] },
    { code: 'M-P1', sequence: 1, heading: 'Target Overview', requiredBy: 'Engagement scope', minWords: 400,
      guidance: 'Corporate history, group structure, activities, markets, assets and workforce of the target.',
      sourceRequirements: ['ECMA-C-001', 'ECMA-C-003', 'ECMA-L-003'] },
    { code: 'M-P2', sequence: 2, heading: 'Financial Due Diligence Findings', requiredBy: 'Engagement scope', minWords: 600,
      guidance: 'Quality of earnings, normalised EBITDA, net debt, working capital, and the adjustments proposed to the price.',
      sourceRequirements: ['ECMA-F-001', 'ECMA-F-002', 'MA-005'] },
    { code: 'M-P3', sequence: 3, heading: 'Legal Due Diligence Findings', requiredBy: 'Engagement scope', minWords: 600,
      guidance: 'Title to shares, corporate standing, material contracts, litigation, property, employment and regulatory compliance.',
      sourceRequirements: ['ECMA-L-001', 'ECMA-L-002', 'ECMA-L-003', 'ECMA-L-005'] },
    { code: 'M-P4', sequence: 4, heading: 'Tax Due Diligence Findings', requiredBy: 'Engagement scope', minWords: 350,
      guidance: 'Historic exposures, open assessments, transfer pricing and the tax structuring of the transaction.',
      sourceRequirements: ['ECMA-T-001', 'ECMA-T-002', 'ECMA-T-003'] },
    { code: 'M-P5', sequence: 5, heading: 'Regulatory Approvals', requiredBy: 'Proc. 813/2013', minWords: 300,
      guidance: 'Competition notification analysis, sector approvals and the conditions each imposes on completion.',
      sourceRequirements: ['MA-003', 'ECMA-R-002'] },
    { code: 'M-P6', sequence: 6, heading: 'Valuation and Price', requiredBy: 'Engagement scope', minWords: 450,
      guidance: 'Valuation methods, ranges, the bridge from enterprise to equity value and the adjustment mechanics.',
      sourceRequirements: ['ECMA-F-006', 'MA-005'] },
    { code: 'M-P7', sequence: 7, heading: 'Risk Register and Deal Protections', requiredBy: 'Engagement scope', minWords: 500,
      guidance: 'Each material risk mapped to a warranty, indemnity, price adjustment, escrow or condition precedent.',
      sourceRequirements: ['MA-002', 'ECMA-L-001'] },
    { code: 'M-P8', sequence: 8, heading: 'Integration and Completion Plan', requiredBy: 'Engagement scope', minWords: 350,
      guidance: 'Conditions precedent, completion deliverables, employee transfer and the first-100-days plan.',
      sourceRequirements: ['MA-002', 'MA-006'] },
  ],
  milestones: [
    { name: 'Mandate signed & retainer received', description: 'Scope, fee and timetable agreed; KYC completed.', sequence: 1, offsetDays: 0, feeShare: 0.25 },
    { name: 'Data room opened & request list issued', description: 'Target data room indexed and the information request list issued.', sequence: 2, offsetDays: 21, feeShare: 0.15 },
    { name: 'Red-flag due diligence report', description: 'Red-flag findings delivered to the acquirer\'s board.', sequence: 3, offsetDays: 55, feeShare: 0.2 },
    { name: 'Full due diligence reports delivered', description: 'Legal, financial and tax reports reviewed and signed off.', sequence: 4, offsetDays: 90, feeShare: 0.2 },
    { name: 'Signing', description: 'Transaction agreement executed.', sequence: 5, offsetDays: 120, feeShare: 0.1 },
    { name: 'Completion', description: 'Conditions satisfied and completion effected.', sequence: 6, offsetDays: 160, feeShare: 0.1 },
  ],
};
